### ISSUE TITLE
Orientation Changes after Behavior Is Played

### ISSUE THREAD

**Issue by dstock21** [jimjing/ModularRobotSystemToolKit#6]
If you make a configuration and put it in an "upright" position, and play a behavior for it, then when you attempt to look at the behavior again it could be in a different orientation. This could completely change what the behavior is supposed to do the second time it runs.

**Comment by jimjing** [comment]
Can you describe more about "look at the behavior again"? Did you play the behavior and then pause it by clicking the "play" button, and then resume by clicking the "play" button again? Is the configuration and behavior you used on the server? If so, please let me know their names so i can try it out.

**Comment by dstock21** [comment]
Ah sorry, I meant "look at the configuration again" and it would be different. So if it's upright the first time you hit play, you let it run for a while, press play to stop, and the configuration is sideways, or members could be different relative to each other, and if I press play again the behavior would play out differently. The file I was using was SMORES_Demo (name for both configuration and behavior).

This issue might be related to the fact that I was using velocity mode and setting it to zero when I didn't want a part to move. I was doing it that way so that everything would rotate back to x = 0 when the configuration reset.

**Comment by jimjing** [comment]
So the design idea is: When the behavior is played, the position and orientation of the "Anchor Module" will be recorded as the position and orientation of the whole configuration. When you pause the behavior by clicking the "Play" button again, the configuration will be lifted to mid-air. This is so that the user can choose to load another configuration and run another behavior. The new configuration will be loaded at whatever position and orientation the previous configuration ended at. So that for example, the user can use a car robot to crawl to a stairs and use a snake robot to climb the stairs. What you experience is intended. I agree it is somewhat confusing. Please let me know if you have a better suggestion on this. To start with your original configuration orientation, you need to clear all modules (in the module menu) and load the configuration again.

**Comment by dstock21** [comment]
Ok, I was just thinking about how it was unnecessary to save and load the configuration every time I wanted to test it, but I see where you're coming from. Maybe if you could load the previous configuration when you're in testing mode i.e. not doing a task, because then there isn't really a reason to keep the tested position and configuration.

**Comment by jimjing** [comment]
Ok. I will close this issue and make a new one for "Test/Task mode"
